- src: geerlingguy.apache
  version: 2.1.1

- src: geerlingguy.php
  version: 3.5.0

- src: geerlingguy.composer
  version: 1.6.1

- src: geerlingguy.git
  version: 1.4.0

- src: geerlingguy.mysql
  version: 2.8.0

- src: geerlingguy.postgresql
  version: 1.3.1

- src: geerlingguy.solr
  version: 3.6.3

- src: geerlingguy.java
  version: 1.7.4

- src: geerlingguy.drupal
  version: 2.4.0

- src: geerlingguy.drush
  version: 2.0.1

- src: geerlingguy.drupal-console
  version: 1.1.0

- src: https://github.com/Islandora-Devops/ansible-role-activemq
  name: Islandora-Devops.activemq
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-alpaca
  name: Islandora-Devops.alpaca
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-apix
  name: Islandora-Devops.apix
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-blazegraph
  name: Islandora-Devops.blazegraph
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-cantaloupe
  name: Islandora-Devops.cantaloupe
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-crayfish
  name: Islandora-Devops.crayfish
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-drupal-openseadragon
  name: Islandora-Devops.drupal-openseadragon
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-fcrepo
  name: Islandora-Devops.fcrepo
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-fcrepo-syn
  name: Islandora-Devops.fcrepo-syn
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-tomcat8
  name: Islandora-Devops.tomcat8
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-fits
  name: Islandora-Devops.fits
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-grok
  name: Islandora-Devops.grok
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-karaf
  name: Islandora-Devops.karaf
  version: 0.0.1

- src: https://github.com/Islandora-Devops/ansible-role-keymaster
  name: Islandora-Devops.keymaster
  version: 0.0.1
