- src: geerlingguy.apache
  version: 2.1.1

- src: geerlingguy.php
  version: 3.5.0

- src: geerlingguy.composer
  version: 1.6.1

- src: geerlingguy.git
  version: 1.4.0

- src: geerlingguy.mysql
  version: 2.8.0

- src: geerlingguy.postgresql
  version: 1.3.1

- src: geerlingguy.solr
  version: 3.6.3

- src: geerlingguy.java
  version: 1.7.4

- src: geerlingguy.drupal
  version: 2.4.0

- src: geerlingguy.drush
  version: 2.0.1

- src: geerlingguy.drupal-console
  version: 1.1.0

- src: Islandora-Devops.activemq
  version: 0.0.1

- src: Islandora-Devops.alpaca
  version: 0.0.1

- src: Islandora-Devops.apix
  version: 0.0.1

- src: Islandora-Devops.blazegraph
  version: 0.0.1

- src: Islandora-Devops.cantaloupe
  version: 0.0.1

- src: Islandora-Devops.crayfish
  version: 0.0.1

- src: Islandora-Devops.drupal-openseadragon
  version: 0.0.1

- src: Islandora-Devops.fcrepo
  version: 0.0.1

- src: Islandora-Devops.fcrepo-syn
  version: 0.0.1

- src: Islandora-Devops.tomcat8
  version: 0.0.1

- src: Islandora-Devops.fits
  version: 0.0.1

- src: Islandora-Devops.grok
  version: 0.0.1

- src: Islandora-Devops.karaf
  version: 0.0.1

- src: Islandora-Devops.keymaster
  version: 0.0.1
