---

- hosts: webserver
  become: yes

  roles:
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.git
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - geerlingguy.drupal
    - Islandora-Devops.drupal-openseadragon
    - webserver-app
