---

drupal_build_composer_project: true
drupal_composer_install_dir: /var/www/html/drupal
drupal_core_owner: "{{ ansible_user }}"
drupal_composer_project_package: "islandora/drupal-project:dev-8.x-1.x"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
drupal_core_path: "{{ drupal_composer_install_dir }}/web"
drupal_db_user: root
drupal_db_password: islandora
drupal_db_name: drupal8
drupal_db_backend: mysql
drupal_db_host: "127.0.0.1"
drupal_domain: "claw.dev"
drupal_site_name: "Islandora-CLAW"
drupal_install_profile: standard
drupal_account_name: admin
drupal_account_pass: islandora
drupal_enable_modules:
  - rdf
  - responsive_image
  - syslog
  - serialization
  - basic_auth
  - rest
  - simpletest
  - restui
  - media_entity
  - media_entity_image
  - devel
  - search_api
  - islandora
  - islandora_collection
  - islandora_image
  - bootstrap

drupal_trusted_hosts:
  - ^localhost$

drupal_trusted_hosts_file: "{{ drupal_core_path }}/sites/default/settings.php"
drupal_services_file: "{{ drupal_core_path }}/sites/default/services.yml"
drupal_public_filesystem: "{{ drupal_core_path }}/sites/default/files"
drupal_public_filesystem_user: www-data

drupal_config_override:
  - configname: openseadragon.settings
    key: iiif_server
    value: "'http://localhost:8080/cantaloupe/iiif/2'"
